# Generated by Django 4.0.1 on 2022-02-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_address_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
