# Generated by Django 4.0.1 on 2022-02-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_strategy_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="content",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
