# Generated by Django 4.0.1 on 2022-01-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="diff",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name="trade",
            name="entry_point",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name="trade",
            name="exit_point",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
