# Generated by Django 4.0.1 on 2022-04-05 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_frame', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('currency_graph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trades.currencypair')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
